import * as THREE from 'three';import {OrbitControls} from './vendor/three/controls/OrbitControls.js';import {GLTFLoader} from './vendor/three/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s),el=$('#view'),scene=new THREE.Scene();scene.background=new THREE.Color('#f0eee4');
const camera=new THREE.PerspectiveCamera(34,1,.001,10);camera.position.set(.39,.31,.62);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;el.append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-.005,.135,0);controls.enableDamping=true;controls.minDistance=.22;controls.maxDistance=1.5;
scene.add(new THREE.HemisphereLight(0xffffff,0x617447,3));const light=new THREE.DirectionalLight(0xfff0d7,3);light.position.set(1,2,2);scene.add(light);const fill=new THREE.DirectionalLight(0xdce8ff,1.4);fill.position.set(-1,1,-1);scene.add(fill);scene.add(new THREE.GridHelper(.7,14,0xc3cbb7,0xe0e2d6));
let parts=[],items=[],model,selected,jawPivot,expanded=false;
function inspect(mesh){if(selected)selected.material.emissive.setHex(0);selected=mesh;if(!mesh)return;selected.material.emissive.setHex(0x233817);const p=parts.find(p=>p.name===mesh.name);if(!p)return;const box=$('#selection');box.replaceChildren();for(const [tag,text]of [['h3',p.name.replaceAll('_',' ')],['p',`${p.dimensions_mm.join(' × ')} mm · ${p.mass_g} g 재료 기준`],['p',p.note]]){const e=document.createElement(tag);e.textContent=text;box.append(e)}for(const [label,path]of [['STL',p.stl],['STEP',p.step]]){const a=document.createElement('a');a.textContent=label+' ↓';a.href='../'+path;box.append(a)}}
function setExplode(){for(const mesh of items){mesh.position.copy(mesh.userData.base);if(expanded)mesh.position.add(mesh.userData.offset)}}
let loadVersion=0;
async function loadVariant(key){key='b2';const version=++loadVersion;const quad=false;$('#loading').hidden=false;$('#loading').textContent='3D 모델 준비 중…';window.microX=null;
try{const r=await fetch(quad?'../artifacts/q4_parts.json':'../artifacts/parts.json');if(!r.ok)throw Error('parts '+r.status);const nextParts=await r.json();const g=await new GLTFLoader().loadAsync(quad?'../models/q4/micro_x_q4.glb':'../models/micro_x.glb');if(version!==loadVersion){g.scene.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose()}});return}if(model){scene.remove(model);model.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose()}})}parts=nextParts;items=[];selected=null;expanded=false;$('#explode').textContent='분해 보기';$('#jaw').value=0;$('#jaw-value').textContent='0°';$('#parts').replaceChildren();$('#selection').innerHTML='<h3>모델에서 부품을 선택하세요</h3><p>치수 · 재료 질량 추정 · STL · STEP</p>';model=g.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.material=o.material.clone();if(o.name.startsWith('eye_'))o.material.roughness=.2;items.push(o)}});const jaw=items.find(o=>o.name==='jaw');jawPivot=new THREE.Group();jawPivot.position.set(.059,0,.212);model.add(jawPivot);model.updateMatrixWorld(true);jawPivot.attach(jaw);for(const mesh of items){mesh.userData.base=mesh.position.clone();const p=parts.find(p=>p.name===mesh.name);mesh.userData.offset=new THREE.Vector3(p.group==='tail'?-.07:p.group==='head'||p.group==='jaw'?.045:0,mesh.name.includes('left')?.07:mesh.name.includes('right')?-.07:0,p.name==='torso_upper'?.07:p.group==='head'?.06:0)}model.rotation.x=-Math.PI/2;$('#part-count').textContent=parts.length;$('#mass').textContent=parts.reduce((s,p)=>s+p.mass_g,0).toFixed(0)+' g';for(const p of parts){const tr=document.createElement('tr');const name=document.createElement('td'),b=document.createElement('button');b.textContent=p.name.replaceAll('_',' ');b.onclick=()=>{inspect(items.find(m=>m.name===p.name));$('#selection').scrollIntoView({behavior:'smooth',block:'center'})};name.append(b);tr.append(name);for(const text of [p.dimensions_mm.join(' × '),p.mass_g+' g']){const td=document.createElement('td');td.textContent=text;tr.append(td)}const td=document.createElement('td');for(const [label,path]of [['STL',p.stl],['STEP',p.step]]){const a=document.createElement('a');a.textContent=label+' ↓';a.href='../'+path;td.append(a)}tr.append(td);$('#parts').append(tr)}$('#loading').hidden=true;window.microX={items,parts,inspect,jawPivot,variant:key};$('#motor-count').value=quad?15:13;$('#motor-count').dispatchEvent(new Event('input'));$('#model-name').textContent=quad?'MICRO X Q4':'MICRO X B2';$('#assembly-step').href=quad?'../models/q4/micro_x_q4.step':'../models/micro_x.step';$('#assembly-glb').href=quad?'../models/q4/micro_x_q4.glb':'../models/micro_x.glb';$('#drawing-pdf').href=quad?'../artifacts/drawings_q4.pdf':'../artifacts/drawings.pdf';$('#static-report').href=quad?'../artifacts/q4_validation.json':'../artifacts/interference.json';}catch(e){$('#loading').textContent='모델을 불러오지 못했습니다. GitHub에서 파일을 확인해 주세요.';console.error(e)}}
$('#variant').disabled=true;const initialURL=new URL(location.href);if(initialURL.searchParams.has('model')){initialURL.searchParams.set('model','b2');history.replaceState(null,'',initialURL)}await loadVariant('b2');
$('#explode').onclick=e=>{expanded=!expanded;setExplode();e.target.textContent=expanded?'조립 보기':'분해 보기'};$('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.target.textContent=controls.autoRotate?'회전 끄기':'회전 켜기'};$('#jaw').oninput=e=>{const angle=Number(e.target.value);if(jawPivot)jawPivot.rotation.y=THREE.MathUtils.degToRad(angle);$('#jaw-value').textContent=angle+'°'};$('#reset').onclick=()=>{if(expanded)$('#explode').click();if(controls.autoRotate)$('#rotate').click();$('#jaw').value=0;$('#jaw').dispatchEvent(new Event('input'));$('#camera').value='hero';$('#camera').dispatchEvent(new Event('change'))};$('#camera').onchange=e=>{camera.position.fromArray({hero:[.39,.31,.62],side:[0,.18,.75],front:[.75,.18,0]}[e.target.value]);controls.target.set(-.005,.135,0);controls.update()};$('#save').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='micro-x-p0.png';a.click()};
const raycaster=new THREE.Raycaster();let start;renderer.domElement.onpointerdown=e=>{start=[e.clientX,e.clientY]};renderer.domElement.onpointerup=e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(items,false)[0];if(hit)inspect(hit.object)};
const costIds=['motor-count','motor-price','other-cost','assembly-cost','yield'];function calculate(){const values=costIds.map(id=>Number($('#'+id).value));const [n,p,o,a,y]=values;$('#cost-result').textContent=values.some(v=>!Number.isFinite(v)||v<0)||n>30||!Number.isInteger(n)||y<=0||y>100?'입력 확인':'$'+((n*p+o+a)/(y/100)).toFixed(2)}costIds.forEach(id=>$('#'+id).oninput=calculate);calculate();new ResizeObserver(()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}).observe(el);let visible=true,last=0;new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe(el);renderer.setAnimationLoop(time=>{if(!visible||document.hidden||time-last<33)return;last=time;controls.update();renderer.render(scene,camera)});
