import * as THREE from 'three';import {OrbitControls} from './vendor/three/controls/OrbitControls.js';import {loadRobot,makeStage,CAMERAS} from './rig.js';
const $=s=>document.querySelector(s),el=$('#view');
const {scene,camera,renderer}=makeStage(el);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.14,0);controls.enableDamping=true;controls.minDistance=.2;controls.maxDistance=1.6;
const KOREAN={chassis:'섀시',torso_shell:'몸통 쉘',chest_panel:'가슴 패널',tail_cover:'꼬리 · 배터리 커버',neck_link:'목 링크',head_base:'머리 베이스',head_yoke:'머리 요크',head_frame:'머리 프레임',skull:'두개골 쉘',jaw_beak:'아래턱',left_yaw2roll:'왼쪽 고관절 요·롤 브래킷',right_yaw2roll:'오른쪽 고관절 요·롤 브래킷',left_hip:'왼쪽 고관절 브래킷',right_hip:'오른잽 고관절 브래킷'.replace('오른잽','오른쪽'),left_thigh:'왼쪽 허벅지',right_thigh:'오른쪽 허벅지',left_shin:'왼쪽 종아리',right_shin:'오른쪽 종아리',left_foot:'왼발',right_foot:'오른발',battery_np_f550:'배터리 (NP-F550급)',compute_board:'컴퓨트 보드',camera_module_3:'카메라 모듈'};
const JOINTS={left_hip_yaw:'왼 고관절 요',left_hip_roll:'왼 고관절 롤',left_hip_pitch:'왼 고관절 피치',left_knee:'왼 무릎',left_ankle:'왼 발목',neck_pitch:'목 피치',head_pitch:'머리 피치',head_yaw:'머리 요',head_roll:'머리 롤',jaw:'턱',right_hip_yaw:'오른 고관절 요',right_hip_roll:'오른 고관절 롤',right_hip_pitch:'오른 고관절 피치',right_knee:'오른 무릎',right_ankle:'오른 발목'};
const label=n=>KOREAN[n]||(n.startsWith('servo_')?'서보 · '+(JOINTS[n.slice(6)]||n.slice(6)):n.replaceAll('_',' '));
let robot,selected,exploded=false,replay=null,playing=false,playhead=0,last=0;
function inspect(mesh){if(selected)selected.material.emissive.setHex(0);selected=mesh;if(!mesh)return;mesh.material.emissive.setHex(0x233817);const p=robot.info[mesh.name];if(!p)return;window.dispatchEvent(new CustomEvent('microx-part',{detail:p}));const box=$('#selection');box.replaceChildren();
  const rows=[['h3',label(p.name)],['p',`${p.dimensions_mm.join(' × ')} mm · ${p.printed?`PLA 꽉 찬 기준 ${p.mass_g} g`:`구매품 · 카탈로그 질량 ${p.mass_g} g`} · 부위 ${p.body}`],['p',p.note]];
  for(const [tag,text]of rows){const e=document.createElement(tag);e.textContent=text;box.append(e)}
  if(p.printed)for(const [l,path]of [['STL',p.stl],['STEP',p.step]]){const a=document.createElement('a');a.textContent=l+' ↓';a.href='../'+path;box.append(a)}}
function layer(){const v=$('#layer').value;robot.setVisible(p=>v==='all'||(v==='shell'?p.group==='shell':v==='frame'?p.printed&&p.group!=='shell':v==='purchased'?!p.printed:v==='head'?['head','head_yoke','head_base','jaw','neck'].includes(p.body):v==='legs'?/left_|right_/.test(p.body):p.body==='trunk'))}
function buildJointPanel(){const host=$('#joints');host.replaceChildren();for(const name of robot.rig.qpos_layout.joints){const j=robot.joints[name];const row=document.createElement('label');row.className='joint';const range=name==='jaw'?[0,40]:name.includes('yaw')&&name.includes('head')?[-160,160]:name==='head_roll'?[-12,12]:name.includes('hip_roll')?[-22,22]:name.includes('hip_yaw')?[-25,30]:[-80,80];
  row.innerHTML=`<span>${JOINTS[name]||name}</span><input type="range" min="${range[0]}" max="${range[1]}" step="1" value="0" data-joint="${name}"><output>0°</output>`;host.append(row);
  row.querySelector('input').oninput=e=>{stopReplay();robot.setJoint(name,j.home+THREE.MathUtils.degToRad(Number(e.target.value)));row.querySelector('output').textContent=e.target.value+'°'}}}
function resetJoints(){robot.home();for(const i of document.querySelectorAll('#joints input')){i.value=0;i.nextElementSibling.textContent='0°'}}
function stopReplay(){playing=false;$('#replay-toggle').textContent='보행 기록 재생';}
async function loadReplay(){try{const r=await fetch('../artifacts/compat_replay.json',{cache:'no-store'});if(!r.ok)throw Error();replay=await r.json();$('#replay-status').textContent=`공식 가중치 · ${replay.result.command.join(', ')} 명령 · ${(replay.qpos.length*replay.dt).toFixed(1)}초 · ${replay.result.first_fall_s===null?'넘어짐 없음':'넘어짐 '+replay.result.first_fall_s+'s'} (시뮬레이션 기록)`;$('#replay-toggle').disabled=false}catch{$('#replay-status').textContent='보행 기록을 불러오지 못했습니다.'}}
$('#replay-toggle').onclick=()=>{if(playing){stopReplay();return}if(!replay)return;if(exploded)$('#explode').click();playing=true;playhead=0;$('#replay-toggle').textContent='재생 중지'};
$('#replay-reset').onclick=()=>{stopReplay();resetJoints()};
try{robot=await loadRobot('../');scene.add(robot.root);
  $('#part-count').textContent=robot.parts.parts.length;$('#mass').textContent=(robot.parts.printed_mass_g+robot.parts.purchased_mass_g).toFixed(0)+' g';$('#servo-count').textContent=robot.parts.purchased.filter(p=>p.kind==='actuator').length;
  const tbody=$('#parts');for(const p of [...robot.parts.parts,...robot.parts.purchased]){const tr=document.createElement('tr');const name=document.createElement('td'),b=document.createElement('button');b.textContent=label(p.name);b.onclick=()=>{inspect(robot.meshes.find(m=>m.name===p.name));$('#selection').scrollIntoView({behavior:'smooth',block:'center'})};name.append(b);tr.append(name);
    for(const text of [p.body,p.dimensions_mm.join(' × '),p.mass_g+' g'+(p.printed?'':' (구매)')]){const td=document.createElement('td');td.textContent=text;tr.append(td)}
    const td=document.createElement('td');if(p.printed)for(const [l,path]of [['STL',p.stl],['STEP',p.step]]){const a=document.createElement('a');a.textContent=l+' ↓';a.href='../'+path;td.append(a)}else td.textContent=p.kind;tr.append(td);tbody.append(tr)}
  buildJointPanel();layer();loadReplay();$('#loading').hidden=true;
  window.microX={robot,items:robot.meshes,parts:robot.parts.parts,inspect,scene,camera,renderer,controls,get playing(){return playing},get exploded(){return exploded}};
}catch(e){$("#loading").textContent="모델을 불러오지 못했습니다. GitHub에서 파일을 확인해 주세요.";window.microXError=String(e.stack||e);console.error(e)}
$('#layer').onchange=layer;
$('#explode').onclick=e=>{stopReplay();exploded=!exploded;robot.explode(exploded);e.target.textContent=exploded?'조립 보기':'분해 보기'};
$('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.target.textContent=controls.autoRotate?'회전 끄기':'회전 켜기'};
$('#reset').onclick=()=>{stopReplay();if(exploded)$('#explode').click();if(controls.autoRotate)$('#rotate').click();resetJoints();$('#camera').value='hero';$('#camera').dispatchEvent(new Event('change'))};
$('#camera').onchange=e=>{camera.position.fromArray(CAMERAS[e.target.value]);controls.target.set(0,.14,0);controls.update()};
$('#save').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='micro-x-reva.png';a.click()};
const raycaster=new THREE.Raycaster();let start;renderer.domElement.onpointerdown=e=>{start=[e.clientX,e.clientY]};renderer.domElement.onpointerup=e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5||!robot)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(robot.meshes.filter(m=>m.visible),false)[0];if(hit)inspect(hit.object)};
const costIds=['motor-count','motor-price','other-cost','assembly-cost','yield'];function calculate(){const values=costIds.map(id=>Number($('#'+id).value));const [n,p,o,a,y]=values;$('#cost-result').textContent=values.some(v=>!Number.isFinite(v)||v<0)||n>30||!Number.isInteger(n)||y<=0||y>100?'입력 확인':'$'+((n*p+o+a)/(y/100)).toFixed(2)}costIds.forEach(id=>$('#'+id).oninput=calculate);calculate();
let visible=true;new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe(el);
renderer.setAnimationLoop(time=>{if(!visible||document.hidden||time-last<16)return;const dt=Math.min((time-last)/1000,.1);last=time;if(playing&&replay){playhead+=dt;const i=Math.floor(playhead/replay.dt);if(i>=replay.qpos.length){playhead=0}else{const q=replay.qpos[i];robot.setPose(q);controls.target.set(q[0],.14,-q[1])}}controls.update();renderer.render(scene,camera)});
if(new URLSearchParams(location.search).get('embed')==='lab')document.body.classList.add('lab-embed');
